services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-mini-crm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-mini-crm

  webserver:
    image: nginx:alpine
    container_name: laravel-mini-crm-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-mini-crm

  db:
    image: postgres:15
    container_name: laravel-mini-crm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: minicrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel-mini-crm

  redis:
    image: redis:alpine
    container_name: laravel-mini-crm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-mini-crm

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-mini-crm-queue
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    command: php artisan queue:work --queue=contacts --sleep=3 --tries=3
    networks:
      - laravel-mini-crm

networks:
  laravel-mini-crm:
    driver: bridge

volumes:
  dbdata:
    driver: local
